### ISSUE TITLE
fake issue

### ISSUE THREAD

**Issue by kr1sten0** [xnth97/WePeiYang-iOS#2]
校友好，可以加我进github twt team吗，我也是天大的，希望能贡献绵薄之力 

么么哒呀！

**Comment by xnth97** [comment]
你好，感谢你对twt的关注！twtstudio team仅对天外天工作室成员开放，如有兴趣随时欢迎报名天外天工作室。期待你的加入！

**Comment by kr1sten0** [comment]
soga 多谢么么哒！

**Comment by xnth97** [comment]
要是在新校区的话直接去学活三层天外天工作室就可以了额🌝或者找这位 @guox191
